### ISSUE TITLE
[PE-D][Tester B] `help` command leads to AB3's UG

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-W12-4/tp#108] opened 2023-03-31 17:14 UTC
Similar issue also appears in the UG, where the sample picture is not updated.

This is a medium severity issue as it causes "occasional inconvenience" to the users looking for the UG but functionality is generally not compromised.

![bug 4.png](https://raw.githubusercontent.com/euph00/ped/main/files/c128092d-ec21-4816-b5f1-3fd40399a9cb.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: euph00/ped#4

**Comment by Jayanth-Balasubramanian** [comment] 2023-04-08 07:56
Duplicate of #101

**Closed** 2023-04-08 07:56 UTC
